export const SIC_LABELS: Record<string, string> = {
  "41201": "Construction of commercial buildings",
  "41202": "Construction of domestic buildings",
  "43220": "Plumbing, heat and air-conditioning installation",
  "43910": "Roofing activities",
  "46190": "Agents involved in the sale of a variety of goods",
  "46370": "Wholesale of coffee, tea, cocoa and spices",
  "47410": "Retail sale of computers, peripheral units and software",
  "46711": "Wholesale of petroleum and petroleum products",
  "46900": "Non-specialised wholesale trade",
  "47820": "Retail sale via stalls and markets of textiles, clothing and footwear",
  "47890": "Retail sale via stalls and markets of other goods",
  "47749": "Retail sale of medical and orthopaedic goods",
  "47910": "Retail sale via mail order houses or via Internet",
  "49320": "Taxi operation",
  "52290": "Other transportation support activities",
  "56101": "Licensed restaurants",
  "56102": "Unlicensed restaurants and cafes",
  "56103": "Take-away food shops and mobile food stands",
  "58110": "Book publishing",
  "61200": "Wireless telecommunications activities",
  "62012": "Business and domestic software development",
  "62020": "Information technology consultancy",
  "62090": "Other information technology service activities",
  "63110": "Data processing, hosting and related activities",
  "64209": "Activities of holding companies",
  "68100": "Buying and selling real estate",
  "68209": "Other letting and operating of own or leased real estate",
  "68310": "Real estate agencies",
  "68320": "Management of real estate on a fee or contract basis",
  "69201": "Accounting and auditing activities",
  "69202": "Bookkeeping activities",
  "69203": "Tax consultancy",
  "70210": "Public relations and communications activities",
  "70229": "Business and management consultancy",
  "74909": "Other professional, scientific and technical activities",
  "71129": "Engineering activities",
  "73110": "Advertising agencies",
  "74100": "Specialised design activities",
  "77110": "Renting and leasing of cars and light motor vehicles",
  "78109": "Other activities of employment placement agencies",
  "82301": "Activities of exhibition and fair organisers",
  "82911": "Activities of collection agencies",
  "82990": "Other business support service activities",
  "85590": "Other education",
  "86220": "Specialists medical practice activities",
  "86900": "Other human health activities",
  "87900": "Other residential care activities",
  "90010": "Performing arts",
  "90030": "Artistic creation",
  "96040": "Physical well-being activities",
  "88100": "Social work activities without accommodation for the elderly and disabled",
  "96020": "Hairdressing and other beauty treatment",
  "96090": "Other service activities",
  "99999": "Dormant company",
}
